spring:  
  application:
    name: adjustment-service
server:  
 port: ${PORT:3333}
eureka:  
 client:
  serviceUrl:
   defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
 instance:
  leaseRenewalIntervalInSeconds: 1
  leaseExpirationDurationInSeconds: 2   
ribbon:
  eureka:
    enabled: true
  # for spring boot ribbon without eureka(ribbon.eureka.enable=false) refer http://www.baeldung.com/spring-cloud-rest-client-with-netflix-ribbon